neiybor/heroku-buildpack-static

scripts/config/templates/nginx.conf.erb
Reverts neiybor/heroku-buildpack-static#13
=> Revert "exclude robots.txt from rendertron served requests"

scripts/config/templates/nginx.conf.erb
Reverts neiybor/heroku-buildpack-static#14
=> Revert "Revert "exclude robots.txt from rendertron served requests""

scripts/config/templates/nginx.conf.erb
Reverts neiybor/heroku-buildpack-static#21
=> Revert "make the trailing slash on proxies optional instead of always present"

scripts/config/templates/nginx.conf.erb
=> Fixed trailing slash issues in link redirect by moving position

scripts/config/templates/nginx.conf.erb
This reverts commit 7a27876f46793a6f6c9f6581e49b99ab88510f31.
=> Revert "test redirect fix"

scripts/config/templates/nginx.conf.erb
Reverts neiybor/heroku-buildpack-static#32
=> Revert "Revert "test redirect fix""

scripts/config/lib/ngx_mruby/locations_double_path.rb, scripts/config/lib/ngx_mruby/locations_single_path.rb, scripts/config/templates/nginx.conf.erb
Here is the PR adding the locations redirect to the nginx configuration.
**Demo Videos**
https://user-images.githubusercontent.com/59292940/117065839-331da080-ace5-11eb-9917-44b01f293ba9.mp4
https://user-images.githubusercontent.com/59292940/117065843-344ecd80-ace5-11eb-8a06-fe0bd1082845.mp4
=> Add locations redirect

scripts/config/lib/ngx_mruby/listing_path.rb, scripts/config/lib/ngx_mruby/locations_double_path.rb, scripts/config/lib/ngx_mruby/locations_single_path.rb, scripts/config/lib/ngx_mruby/regions_path.rb, scripts/config/templates/nginx.conf.erb
Add support for unicode chars in the redirects for the url migration
**Demo Video**
https://user-images.githubusercontent.com/59292940/117080031-3c653800-acfa-11eb-9eb0-2ca7d0d6ffff.mp4
=> add support for unicode characters in redirects

scripts/config/templates/nginx.conf.erb
Reference this link to see why I did it this way: https://ubiq.co/tech-blog/remove-trailing-slash-in-nginx/
=> redirect-trailing slashes

scripts/config/templates/nginx.conf.erb
Reverts neiybor/heroku-buildpack-static#44
=> Revert "redirect-trailing slashes"

scripts/config/templates/nginx.conf.erb
Reverts neiybor/heroku-buildpack-static#46
=> Revert "redirect trailing slashes unless its the blog"

scripts/config/templates/nginx.conf.erb
=> add ip chain log

scripts/config/templates/nginx.conf.erb
Reverts neiybor/heroku-buildpack-static#60
=> Revert "Update error string"

scripts/config/templates/nginx.conf.erb
Split Heroku/AWS SSR traffic 50/50 instead of 95/5.
=> NED-8337 - Give AWS SSR 50% of traffic

scripts/config/lib/nginx_config.rb, scripts/config/templates/nginx.conf.erb
* NED-8337 - Move ssr-frontend traffic 100% to AWS (#84)
=> Buildpack release #2 2022-07-25

scripts/config/lib/nginx_config.rb, scripts/config/lib/ngx_mruby/dlp_redirect_path.rb, scripts/config/templates/nginx.conf.erb
Remove reference to prerender url
=> Take out Prerender Rules

scripts/config/templates/nginx.conf.erb
Reverts neiybor/heroku-buildpack-static#106
=> Revert "NED-11212 - Redirect individual college URLs to city/state URL"

scripts/config/lib/ngx_mruby/regions_path.rb
Reverts neiybor/heroku-buildpack-static#113
=> Revert "Add condition for fleet-parking search"

scripts/config/templates/nginx.conf.erb
* Add condition for fleet-parking search (#113)
* Fix fleet-parking search route
* Fix regex
Co-authored-by: erikprusse <94488028+erikprusse@users.noreply.github.com>
=> Merge staging into master

scripts/config/templates/nginx.conf.erb
Add proxy routing for new commercial landing pages which are hosted on `ssr-frontend`.
=> NED-12242 Create Commercial Web Pages

.gitignore, scripts/config/lib/ngx_mruby/dlp_redirect_path.rb, scripts/config/templates/nginx.conf.erb
NED-12747
We have a redirect for dlp urls with uppercase letters, but we are missing redirects for 24-storage.
=> Add 24-hour storage DLPS to uppercase url redirect.

scripts/config/lib/ngx_mruby/dlp_redirect_path.rb, scripts/config/templates/nginx.conf.erb
NED-12747
This will change the following urls: 
/* -near-me/Alabama/gadsden
/* -near-me/alabama/Gadsden
/* -near-me/Alabama/Gadsden
/* -near-me/alAbama/gadsden
/* -near-me/alAbama/GaDsden
to 
/* -near-me/alabama/gadsden
=> Redirect urls with any uppercase letters in city or state to lowercase.

scripts/config/lib/ngx_mruby/dlp_redirect_path.rb, scripts/config/templates/nginx.conf.erb
Reverts neiybor/heroku-buildpack-static#138
=> Revert "Redirect urls with any uppercase letters in city or state to lowercase."

scripts/config/templates/nginx.conf.erb
add turo redirect link to heroku buildpack static (#145)
=> Prod Release

scripts/config/templates/nginx.conf.erb
Here are some nginx routing rules for changing /commercial to /business
=> ENG-451 change /commercial to /business

scripts/config/templates/nginx.conf.erb
This rule will proxy the /host page to SSR frontend
=> /host page proxy to ssr

scripts/config/templates/nginx.conf.erb
Reverts neiybor/heroku-buildpack-static#192
=> Revert "take 2"

scripts/config/templates/nginx.conf.erb
* speedy make ff persist
* revert speedy assignment cookie name change
=> heroku-buildpack-static release 10/12/2023

scripts/config/templates/nginx.conf.erb
* fix ssr-resources proxy
* swap
---------
=> fix ssr-resources proxy (#226)

scripts/config/templates/nginx.conf.erb
=> Prod Release 04/09/24

scripts/config/templates/nginx.conf.erb
Reverts neiybor/heroku-buildpack-static#239
=> Revert "rm homepage->auth redirect"

scripts/config/templates/nginx.conf.erb
Revert "rm homepage->auth redirect (#239)" (#242)
This reverts commit 7afbabe5a27b5bcf83a139734ad0be463bc1a930.
=> heroku-buildpack-static release 5/22/2024

scripts/config/templates/nginx.conf.erb
This didn't work in staging, so we are removing it and handling this logic in ssr-frontend
=> Remove trailing question mark logic
